### ISSUE TITLE
Incompatible with "Create Fabric Sodium Fix"

### ISSUE THREAD

**Issue by dasaikuru** [alexandsr/BellsAndWhistlesMod#19]
Having the _Create Fabric Sodium Fix_ installed along side _Bells & Whistles_ does not allow Minecraft to launch, despite it being the correct version.

```
Incompatible mods found!
net.fabricmc.loader.impl.FormattedException: Some of your mods are incompatible with the game or each other!
A potential solution has been determined, this may resolve your problem:
	 - Replace mod 'Create' (create) 0.5.1-d-build.5+mc1.20.1 with version 0.5.1-d-build.1161+mc1.20.1.
More details:
	 - Mod 'Create: Bells & Whistles' (bellsandwhistles) 0.4.4 requires version 0.5.1-d-build.1161+mc1.20.1 of mod 'Create' (create), but only the wrong version is present: 0.5.1-d-build.5+mc1.20.1!
	 - Mod 'Fastload Fabric-api Forwarding' (fastload_fapi_forward) 1.0.2 requires version 1.18.2 of 'Minecraft' (minecraft), but only the wrong version is present: 1.20.1!
	at net.fabricmc.loader.impl.FormattedException.ofLocalized(FormattedException.java:51)
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:194)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:146)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

```

**Comment by a0ax** [comment]
Fixed in a new release is up on curseforge, modrinth and github at this time. Thanks for the issue and the log, very useful.
